farewell_responses = [
    "¡Hasta luego, {name}!",
    "Adiós por ahora, {name}",
    "Que tenga un buen día, {title} {name}.",
    "Que tenga un día lleno de éxitos, {title} {name}. Hasta pronto.",
    "Hasta la próxima, {title} {name}. Siempre estoy aquí si me necesita.",
    "Adiós por ahora, {name}. Que sus proyectos sean fructíferos.",
    "¡Nos vemos pronto, {name}!",
    "Que tenga una tarde maravillosa, {name}.",
    "Adiós por ahora, {name}. Si necesita algo más, no dude en llamarme.",
    "¡Hasta pronto, {name}! Estaré aquí cuando me necesite.",
    "Adiós, {name}. Que tenga un día lleno de logros.",
    "Que tenga un día fenomenal, {name}. Nos vemos después.",
    "Espero verle de nuevo pronto, {name}. Cuídese.",
    "Que pase un buen día, {name}. Hasta la próxima.",
    "Cuídese, {title} {name}. Hasta luego.",
    "Nos vemos luego, {name}. Que todo le vaya bien.",
    "Que tenga una excelente jornada, {name}. Adiós.",
    "Hasta más ver, {name}. Que tenga un día productivo.",
    "Espero que su día sea maravilloso, {name}. Hasta luego.",
    "Que le vaya muy bien, {name}. Nos vemos pronto.",
    "Disfrute su día, {name}. Hasta la próxima.",
    "Le deseo lo mejor, {title} {name}. Nos vemos después.",
    "Cuídese mucho, {name}. Hasta pronto.",
    "Espero que tenga un día fantástico, {name}. Hasta luego.",
    "Le deseo un excelente día, {title} {name}. Hasta la próxima."
]
