greetings = [
    "¡Hola, {title} {name}! ¿Cómo puedo ayudarle?",
    "¿Qué puedo hacer por usted, {title} {name}?",
    "Dígame, {title} {name}, ¿Qué necesita?",
    "Buenos días, {title} {name}. ¿Cómo puedo asistirle hoy?",
    "¡Saludos, {title} {name}! ¿En qué puedo servirle?",
    "Hola, {title} {name}. Estoy a su disposición para cualquier solicitud que tenga.",
    "¡Buen día, {title} {name}! ¿En qué puedo serle útil hoy?",
    "¡Hola, {title} {name}! ¿Qué puedo hacer por usted hoy?",
    "¿Cómo está, {title} {name}? ¿En qué puedo asistirle?",
    "¡Buenos días, {title} {name}! Estoy aquí para ayudarle.",
    "Hola, {title} {name}. ¿Qué necesita que haga hoy?",
    "¡Saludos cordiales, {title} {name}! ¿Cómo puedo asistirle?",
    "Buenos días, {title} {name}. ¿En qué puedo ayudarle hoy?",
    "¡Hola, {title} {name}! ¿En qué puedo servirle esta mañana?",
    "¿Qué necesita hoy, {title} {name}? Estoy aquí para ayudarle.",
    "Dígame, {title} {name}. ¿En qué puedo serle útil?",
    "¡Hola, {title} {name}! ¿Cómo puedo hacer su día mejor?",
    "Buenos días, {title} {name}. ¿Qué puedo hacer por usted?",
    "¡Saludos, {title} {name}! ¿En qué puedo asistirle hoy?",
    "Hola, {title} {name}. ¿Cómo puedo ayudarle en este momento?",
    "¡Buen día, {title} {name}! Estoy listo para ayudarle.",
    "Hola, {title} {name}. ¿Qué puedo hacer para usted hoy?",
    "Buenos días, {title} {name}. ¿Cómo puedo serle útil?",
    "¡Hola, {title} {name}! Estoy a su servicio para lo que necesite.",
    "¿Cómo puedo asistirle hoy, {title} {name}? Estoy aquí para ayudar."
]
