not_understood_responses = [
    "No le he entendido, {title} {name}.",
    "No pude entender lo que dijo, {title} {name}. ¿Podría repetirlo?",
    "Lo siento, {title} {name}. No entendí eso.",
    "Parece que hubo un error de comunicación, {title} {name}. ¿Podría repetir eso, por favor?",
    "Mis disculpas, {title} {name}. Parece que mi procesamiento no fue claro esta vez.",
    "Lo siento, {title} {name}. Parece que mi interpretación fue un poco borrosa. ¿Podría intentarlo de nuevo?",
    "No estoy seguro de haber entendido bien, {title} {name}. ¿Podría decirlo otra vez?",
    "No comprendí lo que dijo, {title} {name}. ¿Podría repetirlo, por favor?",
    "Perdón, {title} {name}. No capté eso. ¿Podría decirlo de nuevo?",
    "Lo siento, {title} {name}. No logré entender lo que dijo.",
    "Parece que no entendí bien, {title} {name}. ¿Podría repetirlo?",
    "No estoy seguro de lo que dijo, {title} {name}. ¿Podría repetirlo, por favor?",
    "Perdón, {title} {name}. No entendí. ¿Podría intentarlo de nuevo?",
    "Disculpe, {title} {name}. No pude comprender eso. ¿Podría decirlo otra vez?",
    "Lamentablemente no entendí, {title} {name}. ¿Podría repetirlo?",
    "No capté su mensaje, {title} {name}. ¿Podría intentarlo de nuevo?",
    "Perdóneme, {title} {name}. No entendí bien. ¿Podría repetir eso?",
    "Lo siento, {title} {name}. No comprendí lo que dijo. ¿Podría decirlo nuevamente?",
    "Parece que hubo un malentendido, {title} {name}. ¿Podría repetir eso?",
    "Disculpe, {title} {name}. No entendí lo que mencionó. ¿Podría intentarlo otra vez?",
    "Perdón, {title} {name}. No entendí bien. ¿Podría decirlo de nuevo?",
    "No logré captar su mensaje, {title} {name}. ¿Podría repetirlo?",
    "Mis disculpas, {title} {name}. No comprendí eso. ¿Podría decirlo otra vez?",
    "Lo siento, {title} {name}. No entendí correctamente. ¿Podría repetirlo?"
]
